// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrJrN7gfOYi1xam8VH0T8kCfXCGXTTOXk',
    appId: '1:101360326399:web:707f8b464ad51834c75eca',
    messagingSenderId: '101360326399',
    projectId: 'klikol-fde77',
    authDomain: 'klikol-fde77.firebaseapp.com',
    storageBucket: 'klikol-fde77.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUfdxHhLHaOx8pnheHE-35e2Iy5xoI3YI',
    appId: '1:101360326399:android:c475b45a69c3bc01c75eca',
    messagingSenderId: '101360326399',
    projectId: 'klikol-fde77',
    storageBucket: 'klikol-fde77.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBccjVp7g06e5Bch24iO4dpR0ZIxct8Kzw',
    appId: '1:101360326399:ios:5ea5df891535194fc75eca',
    messagingSenderId: '101360326399',
    projectId: 'klikol-fde77',
    storageBucket: 'klikol-fde77.firebasestorage.app',
    iosBundleId: 'com.example.klikol',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBccjVp7g06e5Bch24iO4dpR0ZIxct8Kzw',
    appId: '1:101360326399:ios:5ea5df891535194fc75eca',
    messagingSenderId: '101360326399',
    projectId: 'klikol-fde77',
    storageBucket: 'klikol-fde77.firebasestorage.app',
    iosBundleId: 'com.example.klikol',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBrJrN7gfOYi1xam8VH0T8kCfXCGXTTOXk',
    appId: '1:101360326399:web:2a6f96145903c2f0c75eca',
    messagingSenderId: '101360326399',
    projectId: 'klikol-fde77',
    authDomain: 'klikol-fde77.firebaseapp.com',
    storageBucket: 'klikol-fde77.firebasestorage.app',
  );
}
